Repository NOW-SOPT-APP7-GS-HOMETOWN/GsHometown-iOS, pull requests merged in 2024-05, with the labels that each got.

#3 [Chore] 프로젝트 세팅
  .gitignore
  GsHometown-iOS/GsHometown-iOS.xcodeproj/project.pbxproj
  GsHometown-iOS/GsHometown-iOS.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  GsHometown-iOS/GsHometown-iOS.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Labels: ASAP, Chore

#5 [Feat] 메인페이지 Compositional Layout 세팅
  GsHometown-iOS/GsHometown-iOS.xcodeproj/project.pbxproj
  GsHometown-iOS/GsHometown-iOS/Common/Extension/UICollectionViewCell+.swift
  GsHometown-iOS/GsHometown-iOS/Common/Extension/UICollectionViewLayout+.swift
  GsHometown-iOS/GsHometown-iOS/Common/Resources/Images/Assets.xcassets/Mock/Contents.json
  GsHometown-iOS/GsHometown-iOS/Common/Resources/Images/Assets.xcassets/Mock/mockAdLarge.imageset/Contents.json
  GsHometown-iOS/GsHometown-iOS/Common/Resources/Images/Assets.xcassets/Mock/mockAdLarge.imageset/hrzt_under_bnr.png
  GsHometown-iOS/GsHometown-iOS/Common/Resources/Images/Assets.xcassets/Mock/mockAdSmall.imageset/Contents.json
  GsHometown-iOS/GsHometown-iOS/Common/Resources/Images/Assets.xcassets/Mock/mockAdSmall.imageset/Frame 2060.png
  GsHometown-iOS/GsHometown-iOS/Common/Resources/Images/Assets.xcassets/Mock/mockBanner.imageset/Contents.json
  GsHometown-iOS/GsHometown-iOS/Common/Resources/Images/Assets.xcassets/Mock/mockBanner.imageset/Frame 95.png
  GsHometown-iOS/GsHometown-iOS/Common/Resources/Images/GSImage.swift
  GsHometown-iOS/GsHometown-iOS/Common/Resources/Info.plist
  GsHometown-iOS/GsHometown-iOS/Info.plist
  GsHometown-iOS/GsHometown-iOS/Model/Advertisement.swift
  GsHometown-iOS/GsHometown-iOS/View/Home/Cell/ConvenienceCell.swift
  GsHometown-iOS/GsHometown-iOS/View/Home/Cell/EventCell.swift
  GsHometown-iOS/GsHometown-iOS/View/Home/Cell/EventOfTheWeekCell.swift
  GsHometown-iOS/GsHometown-iOS/View/Home/Cell/OrderServiceCell.swift
  GsHometown-iOS/GsHometown-iOS/View/Home/Cell/PageCell.swift
  GsHometown-iOS/GsHometown-iOS/View/Home/Cell/ServiceCell.swift
  GsHometown-iOS/GsHometown-iOS/View/Home/HomeViewController.swift
  GsHometown-iOS/GsHometown-iOS/View/Home/Type/ConvenienceType.swift
  GsHometown-iOS/GsHometown-iOS/View/Home/Type/HomeSectionType.swift
  GsHometown-iOS/GsHometown-iOS/View/Home/Type/OrderServiceType.swift
  GsHometown-iOS/GsHometown-iOS/View/Home/Type/PageType.swift
  GsHometown-iOS/GsHometown-iOS/View/Home/Type/ServiceType.swift
Labels: Feature, 지석

#13 [Feat] 언제나 가까이 ~ 하단배너 UI 디테일 구현
  GsHometown-iOS/GsHometown-iOS/Common/Extension/UICollectionViewLayout+.swift
  GsHometown-iOS/GsHometown-iOS/View/Home/Cell/EventOfTheWeekCell.swift
Labels: Feature, 지석

#15 [Feat] 상단 네비게이션 바 구현
  GsHometown-iOS/GsHometown-iOS.xcodeproj/project.pbxproj
  GsHometown-iOS/GsHometown-iOS/Common/Components/GSNavigationBar.swift
  GsHometown-iOS/GsHometown-iOS/Common/Resources/Images/Assets.xcassets/Icon/ic_robot.imageset/Contents.json
  GsHometown-iOS/GsHometown-iOS/Common/Resources/Images/Assets.xcassets/Icon/ic_robot.imageset/state=normal@3x.png
  GsHometown-iOS/GsHometown-iOS/Common/Resources/Images/GSImage.swift
  GsHometown-iOS/GsHometown-iOS/View/Home/HomeViewController.swift
  GsHometown-iOS/GsHometown-iOS/View/Home/ReusableView/EventReusableView.swift
  GsHometown-iOS/GsHometown-iOS/View/Home/ReusableView/ServiceReusableView.swift
Labels: Feature, 지석

#24 [Feat] DTO 세팅
  GsHometown-iOS/GsHometown-iOS/Network/DTO/DTO.swift
  GsHometown-iOS/GsHometown-iOS/Network/DTO/Request/DTO+DeleteLikeRequest.swift
  GsHometown-iOS/GsHometown-iOS/Network/DTO/Request/DTO+GetDetailProductRequest.swift
  GsHometown-iOS/GsHometown-iOS/Network/DTO/Request/DTO+GetHomeRequest.swift
  GsHometown-iOS/GsHometown-iOS/Network/DTO/Request/DTO+GetPreorderInfoRequest.swift
  GsHometown-iOS/GsHometown-iOS/Network/DTO/Request/DTO+PostLikeRequest.swift
  GsHometown-iOS/GsHometown-iOS/Network/DTO/Request/dummy8.swift
  GsHometown-iOS/GsHometown-iOS/Network/DTO/Response/DTO+DeleteLikeResponse.swift
  GsHometown-iOS/GsHometown-iOS/Network/DTO/Response/DTO+GetDetailProductResponse.swift
  GsHometown-iOS/GsHometown-iOS/Network/DTO/Response/DTO+GetHomeResponse.swift
  GsHometown-iOS/GsHometown-iOS/Network/DTO/Response/DTO+GetPreorderInfoResponse.swift
  GsHometown-iOS/GsHometown-iOS/Network/DTO/Response/DTO+PostLikeResponse.swift
  GsHometown-iOS/GsHometown-iOS/Network/DTO/Response/dummy9.swift
Labels: Feature, 지석

#26 [Feat] DTO 세팅
  GsHometown-iOS/GsHometown-iOS.xcodeproj/project.pbxproj
Labels: Chore, 지석

#29 [Feat] API Target 구현
  GsHometown-iOS/GsHometown-iOS.xcodeproj/project.pbxproj
  GsHometown-iOS/GsHometown-iOS/Common/Resources/Info.plist
  GsHometown-iOS/GsHometown-iOS/Network/APITarget/APITarget+All.swift
  GsHometown-iOS/GsHometown-iOS/Network/APITarget/APITarget+Likes.swift
  GsHometown-iOS/GsHometown-iOS/Network/APITarget/APITarget+Products.swift
Labels: Feature, 지석

#21 [Feat] 하단 커스텀 탭바 구현
  GsHometown-iOS/GsHometown-iOS.xcodeproj/project.pbxproj
  GsHometown-iOS/GsHometown-iOS/Common/Extension/NotificationName+.swift
  GsHometown-iOS/GsHometown-iOS/Common/Resources/Images/Assets.xcassets/Button/homeActive.imageset/state=btn_home_active_andr.png
  GsHometown-iOS/GsHometown-iOS/Common/Resources/Images/Assets.xcassets/Button/homeInactive.imageset/state=btn_home_normal_andr.png
  GsHometown-iOS/GsHometown-iOS/Common/Resources/Images/Assets.xcassets/Button/myActive.imageset/Property 1=btn_my_active_andr.png
  GsHometown-iOS/GsHometown-iOS/Common/Resources/Images/Assets.xcassets/Button/myInactive.imageset/Property 1=btn_my_normal_andr.png
  GsHometown-iOS/GsHometown-iOS/Common/Resources/Images/Assets.xcassets/Button/orderHistoryActive.imageset/Property 1=btn_order_active_andr.png
  GsHometown-iOS/GsHometown-iOS/Common/Resources/Images/Assets.xcassets/Button/orderHistoryInactive.imageset/Contents.json
  GsHometown-iOS/GsHometown-iOS/Common/Resources/Images/Assets.xcassets/Button/orderHistoryInactive.imageset/Property 1=btn_order_normal_andr.png
  GsHometown-iOS/GsHometown-iOS/Common/Resources/Images/Assets.xcassets/Button/payActive.imageset/Contents.json
  GsHometown-iOS/GsHometown-iOS/Common/Resources/Images/Assets.xcassets/Button/payActive.imageset/Property 1=btn_pay_active_andr.png
  GsHometown-iOS/GsHometown-iOS/Common/Resources/Images/Assets.xcassets/Button/payActive.imageset/btn_pay_ios.png
  GsHometown-iOS/GsHometown-iOS/Common/Resources/Images/Assets.xcassets/Button/payInactive.imageset/Contents.json
  GsHometown-iOS/GsHometown-iOS/Common/Resources/Images/Assets.xcassets/Button/payInactive.imageset/Property 1=btn_pay_normal_andr.png
  GsHometown-iOS/GsHometown-iOS/Common/Resources/Images/Assets.xcassets/Button/searchActive.imageset/state=btn_search_active_andr.png
  GsHometown-iOS/GsHometown-iOS/Common/Resources/Images/Assets.xcassets/Button/searchInactive.imageset/state=btn_search_normal_andr.png
  GsHometown-iOS/GsHometown-iOS/Controller/Home/HomeViewController+.swift
  GsHometown-iOS/GsHometown-iOS/View/Home/HomeViewController.swift
  GsHometown-iOS/GsHometown-iOS/View/Home/ReusableView/EventReusableView.swift
  GsHometown-iOS/GsHometown-iOS/View/TabBar/GSTabBarController.swift
  GsHometown-iOS/GsHometown-iOS/View/TabBar/GSTabBarType.swift
Labels: Feature, 지석

#27 [Feat] 배너 광고 구현
  GsHometown-iOS/GsHometown-iOS.xcodeproj/project.pbxproj
  GsHometown-iOS/GsHometown-iOS/Model/Advertisement.swift
  GsHometown-iOS/GsHometown-iOS/View/Home/HomeViewController.swift
  GsHometown-iOS/GsHometown-iOS/View/Home/Type/HomeSectionType.swift
Labels: Feature, 지석

#32 [Feat] 마이페이지 UI 구현
  .DS_Store
  GsHometown-iOS/.DS_Store
  GsHometown-iOS/GsHometown-iOS.xcodeproj/project.pbxproj
  GsHometown-iOS/GsHometown-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  GsHometown-iOS/GsHometown-iOS.xcodeproj/project.xcworkspace/xcuserdata/sumin.xcuserdatad/UserInterfaceState.xcuserstate
  GsHometown-iOS/GsHometown-iOS.xcodeproj/xcuserdata/sumin.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  GsHometown-iOS/GsHometown-iOS.xcodeproj/xcuserdata/sumin.xcuserdatad/xcschemes/xcschememanagement.plist
  GsHometown-iOS/GsHometown-iOS/.DS_Store
  GsHometown-iOS/GsHometown-iOS/Application/SceneDelegate.swift
  GsHometown-iOS/GsHometown-iOS/Common/Resources/Images/Assets.xcassets/Icon/stackDivider.imageset/Contents.json
  GsHometown-iOS/GsHometown-iOS/Common/Resources/Images/Assets.xcassets/Icon/stackDivider.imageset/stackDivider.png
  GsHometown-iOS/GsHometown-iOS/Common/Resources/Images/GSImage.swift
  GsHometown-iOS/GsHometown-iOS/Network/.DS_Store
  GsHometown-iOS/GsHometown-iOS/Network/DTO/.DS_Store
  GsHometown-iOS/GsHometown-iOS/View/.DS_Store
  GsHometown-iOS/GsHometown-iOS/View/MyInfo/.DS_Store
  GsHometown-iOS/GsHometown-iOS/View/MyInfo/MyInfoViewController.swift
  GsHometown-iOS/GsHometown-iOS/View/MyInfo/ReusableMenuHeaderView.swift
  GsHometown-iOS/GsHometown-iOS/View/MyInfo/ReusableStackView.swift
  GsHometown-iOS/GsHometown-iOS/View/MyInfo/Type/UserHistoryType.swift
  GsHometown-iOS/GsHometown-iOS/View/MyInfo/Type/UserMenuType.swift
  GsHometown-iOS/GsHometown-iOS/View/MyInfo/Type/UserRewardsType.swift
  GsHometown-iOS/GsHometown-iOS/View/MyInfo/View/.DS_Store
  GsHometown-iOS/GsHometown-iOS/View/MyInfo/View/MyInfoView.swift
  GsHometown-iOS/GsHometown-iOS/View/MyInfo/View/UserInfoView.swift
  GsHometown-iOS/GsHometown-iOS/View/MyInfo/View/UserMenuView.swift
  GsHometown-iOS/GsHometown-iOS/View/MyInfo/dummy3.swift
Labels: Feature, 수민

#36 [Feat] 코디네이터 적용
  GsHometown-iOS/GsHometown-iOS.xcodeproj/project.pbxproj
  GsHometown-iOS/GsHometown-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  GsHometown-iOS/GsHometown-iOS/Application/AppCoordinator.swift
  GsHometown-iOS/GsHometown-iOS/Application/SceneDelegate.swift
  GsHometown-iOS/GsHometown-iOS/Coordinator/Coordinator.swift
  GsHometown-iOS/GsHometown-iOS/Coordinator/FlowCoordinator.swift
  GsHometown-iOS/GsHometown-iOS/Coordinator/PresentationStyle.swift
  GsHometown-iOS/GsHometown-iOS/View/Detail/Flow/DetailCoordinator.swift
  GsHometown-iOS/GsHometown-iOS/View/Home/Cell/OrderServiceCell.swift
  GsHometown-iOS/GsHometown-iOS/View/Home/Flow/HomeCoordinator.swift
  GsHometown-iOS/GsHometown-iOS/View/Home/HomeViewController.swift
  GsHometown-iOS/GsHometown-iOS/View/Home/Type/HomeSectionType.swift
  GsHometown-iOS/GsHometown-iOS/View/PreOrder/Flow/PreOrderCoordinator.swift
  GsHometown-iOS/GsHometown-iOS/View/PreOrder/PreOrderViewController.swift
  GsHometown-iOS/GsHometown-iOS/View/PreOrder/View/AllProductView/AllProductCollectionView.swift
  GsHometown-iOS/GsHometown-iOS/View/PreOrder/View/AllProductView/AllProductView.swift
  GsHometown-iOS/GsHometown-iOS/View/TabBar/Flow/GSTabBarCoordinator.swift
  GsHometown-iOS/GsHometown-iOS/View/TabBar/GSTabBarController.swift
  GsHometown-iOS/GsHometown-iOS/View/TabBar/GSTabBarType.swift
Labels: Feature, 지석

#40 [Feat] HomeView API 연결
  GsHometown-iOS/GsHometown-iOS/Controller/Home/HomeViewController+.swift
  GsHometown-iOS/GsHometown-iOS/View/Home/Cell/EventCell.swift
  GsHometown-iOS/GsHometown-iOS/View/Home/HomeViewController.swift
  GsHometown-iOS/GsHometown-iOS/View/Home/ReusableView/EventReusableView.swift
  GsHometown-iOS/GsHometown-iOS/View/Home/Type/HomeSectionType.swift
Labels: Feature, 지석

#46 [Feat] MyInfo 탭바 연결
  GsHometown-iOS/GsHometown-iOS.xcodeproj/project.pbxproj
  GsHometown-iOS/GsHometown-iOS/View/MyInfo/Flow/MyInfoCoordinator.swift
  GsHometown-iOS/GsHometown-iOS/View/TabBar/Flow/GSTabBarCoordinator.swift
Labels: Feature, 지석

#42 [Feat] DetailView API 연결
  GsHometown-iOS/GsHometown-iOS/Network/APITarget/APITarget+Likes.swift
  GsHometown-iOS/GsHometown-iOS/Network/APITarget/APITarget+Products.swift
  GsHometown-iOS/GsHometown-iOS/Network/DTO/Response/DTO+GetDetailProductResponse.swift
  GsHometown-iOS/GsHometown-iOS/View/Detail/DetailViewController.swift
Labels: Feature, 연서

#44 [Feat] PreOrderView GSPay API 연결
  GsHometown-iOS/GsHometown-iOS.xcodeproj/project.xcworkspace/xcuserdata/sumin.xcuserdatad/UserInterfaceState.xcuserstate
  GsHometown-iOS/GsHometown-iOS.xcodeproj/xcuserdata/sumin.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  GsHometown-iOS/GsHometown-iOS.xcodeproj/xcuserdata/sumin.xcuserdatad/xcschemes/xcschememanagement.plist
  GsHometown-iOS/GsHometown-iOS/Model/DiscountEvent.swift
  GsHometown-iOS/GsHometown-iOS/Model/EventOfTheMonth.swift
  GsHometown-iOS/GsHometown-iOS/Network/DTO/Response/DTO+GetPreorderInfoResponse.swift
  GsHometown-iOS/GsHometown-iOS/View/PreOrder/Cell/DiscountEventCollectionViewCell.swift
  GsHometown-iOS/GsHometown-iOS/View/PreOrder/PreOrderViewController.swift
  GsHometown-iOS/GsHometown-iOS/View/PreOrder/View/BannerView/BannerView.swift
  GsHometown-iOS/GsHometown-iOS/View/PreOrder/View/EventView/DiscountEventCollectionView.swift
  GsHometown-iOS/GsHometown-iOS/View/PreOrder/View/EventView/EventView.swift
  GsHometown-iOS/GsHometown-iOS/View/PreOrder/View/MainView/MainView.swift
Labels: Feature, 수민

#48 [Feat] 합세 마무리 작업
  GsHometown-iOS/GsHometown-iOS.xcodeproj/project.pbxproj
  GsHometown-iOS/GsHometown-iOS/Common/Components/GSNavigationBarWithBackButton.swift
  GsHometown-iOS/GsHometown-iOS/Common/Resources/Images/Assets.xcassets/Icon/backButton.imageset/Contents.json
  GsHometown-iOS/GsHometown-iOS/Common/Resources/Images/Assets.xcassets/Icon/backButton.imageset/Vector 9 (Stroke).png
  GsHometown-iOS/GsHometown-iOS/Common/Resources/Images/Assets.xcassets/Icon/basketButton.imageset/Contents.json
  GsHometown-iOS/GsHometown-iOS/Common/Resources/Images/Assets.xcassets/Icon/basketButton.imageset/Union-2.png
  GsHometown-iOS/GsHometown-iOS/Common/Resources/Images/Assets.xcassets/Icon/homeButton.imageset/Contents.json
  GsHometown-iOS/GsHometown-iOS/Common/Resources/Images/Assets.xcassets/Icon/homeButton.imageset/Union-1.png
  GsHometown-iOS/GsHometown-iOS/Common/Resources/Images/Assets.xcassets/Icon/searchButton.imageset/Contents.json
  GsHometown-iOS/GsHometown-iOS/Common/Resources/Images/Assets.xcassets/Icon/searchButton.imageset/Union.png
  GsHometown-iOS/GsHometown-iOS/Common/Resources/Images/GSImage.swift
  GsHometown-iOS/GsHometown-iOS/View/Detail/DetailViewController.swift
  GsHometown-iOS/GsHometown-iOS/View/Home/HomeViewController.swift
  GsHometown-iOS/GsHometown-iOS/View/Home/ReusableView/EventReusableView.swift
  GsHometown-iOS/GsHometown-iOS/View/MyInfo/MyInfoViewController.swift
Labels: Feature, 지석
